version: "3.7"

services:
  unit:
    build:
      context: ..
      dockerfile: api/Dockerfile
      target: test
    environment:
      - DB_STRING=postgresql://postgres:test@ci_db:5432/postgres
      - SQLALCHEMY_SILENCE_UBER_WARNING=1

  integration:
    depends_on:
      - ci_db
    build:
      context: ..
      dockerfile: api/Dockerfile
      target: test
    environment:
      - DB_STRING=postgresql://postgres:test@ci_db:5432/postgres
      - SQLALCHEMY_SILENCE_UBER_WARNING=1

  ci_db:
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD=test
