"""seed

Revision ID: 0003
Revises: 0002
Create Date: 2025-01-07 20:48:59.908520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    app_user_table = sa.table(
        "app_user",
        sa.Column('id', sa.INTEGER),
        sa.Column('username', sa.VARCHAR),
        sa.Column('hashed_password', sa.VARCHAR),
        sa.Column('disabled', sa.BOOLEAN),
    )    
    op.bulk_insert(app_user_table, [
        {'id':0, 'username':'johndoe', 'hashed_password': 'fakehashedsecret', 'disabled': False },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_user')
    op.create_table('app_user',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='user_pkey'),
        sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
